#!/usr/bin/env python3

import argparse
import motiflib

parser = argparse.ArgumentParser(description='DNA motif drawing program.')
parser.add_argument('fasta', type=str, metavar='<fasta>')
arg = parser.parse_args()


seqs = []
for name, seq in motiflib.read_fasta(arg.fasta):
	seqs.append(seq)

motif = motiflib.seqs2motif(seqs)

svg = motiflib.motif2svg(motif)
print('<html><body>')
print('Testing')
print(svg)
print('</body></html>')